import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,cp,mkdir,symlink,readFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {execFileSync} from 'node:child_process';
import {createServer} from 'node:http';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import {setupMCP} from '../scripts/setup-mcp.mjs';
import {wireMCPRoute} from '../scripts/wire-mcp-route.mjs';
import {verifyMCPRoute} from '../scripts/verify-mcp-route.mjs';

test('clean sample installs, verifies actual dispatch, repeats and rolls back', {timeout:20000},async t=>{
 const root=fileURLToPath(new URL('..',import.meta.url)),project=await mkdtemp(join(tmpdir(),'wd-install-'));
 t.after(()=>rm(project,{recursive:true,force:true}));
 await cp(join(root,'examples/mcp-install'),project,{recursive:true});
 await mkdir(join(project,'node_modules/@webdecoy'),{recursive:true});
 await symlink(process.env.WEBDECOY_INSTALL_SDK_ROOT??root,join(project,'node_modules/@webdecoy/ai-protection'),'dir');
 await symlink(join(root,'node_modules/@types'),join(project,'node_modules/@types'),'dir');
 const options={project,optionsFile:'src/options.ts'},wiring={project,routeFile:'src/server.ts',handlerFile:'src/webdecoy-mcp.ts'};
 const original=await readFile(join(project,'src/server.ts'),'utf8');
 assert.equal((await setupMCP({...options,command:'plan'})).status,'proposed');
 assert.equal((await setupMCP({...options,command:'apply'})).status,'created');
 assert.equal((await wireMCPRoute({...wiring,command:'plan'})).status,'proposed');
 assert.equal((await wireMCPRoute({...wiring,command:'apply'})).status,'wired');
 assert.equal((await setupMCP({...options,command:'apply'})).status,'unchanged');
 assert.equal((await wireMCPRoute({...wiring,command:'apply'})).status,'unchanged');
 const compile=()=>execFileSync(process.execPath,[join(root,'node_modules/typescript/bin/tsc'),'-p',project],{stdio:'pipe',encoding:'utf8'});
 compile();
 let route;const server=createServer((req,res)=>route(req,res));await new Promise(r=>server.listen(0,'127.0.0.1',r));
 t.after(()=>{server.closeAllConnections();return new Promise(r=>server.close(r));});
 const resource=`http://127.0.0.1:${server.address().port}/mcp`;
 const {mcpOptions,counters}=await import(pathToFileURL(join(project,'dist/options.js')));mcpOptions.resource=resource;
 ({route}=await import(pathToFileURL(join(project,'dist/server.js'))));
 assert.equal((await verifyMCPRoute({resource,token:'owned-a'})).passed,true);
 assert.equal(counters.reads,0);
 const client=new Client({name:'clean-install',version:'1'});t.after(()=>client.close());
 await client.connect(new StreamableHTTPClientTransport(new URL(resource),{requestInit:{headers:{Authorization:'Bearer owned-a'}}}));
 assert.equal((await client.callTool({name:'read',arguments:{id:'a'}})).content[0].text,'owned-a');
 for(const [name,args] of [['read',{id:'b'}],['read',{id:'a',agent_id:'admin'}],['admin',{}]])assert.equal((await client.callTool({name,arguments:args})).isError,true);
 assert.equal(counters.reads,1);assert.equal(counters.forbidden,0);
 const controller=new AbortController();
 const pending=fetch(resource,{method:'POST',headers:{Authorization:'Bearer owned-a','Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:88,method:'tools/call',params:{name:'wait',arguments:{}}}),signal:controller.signal}).then(r=>r.text()).catch(()=>{});
 for(let i=0;i<100&&!counters.waiting;i++)await new Promise(r=>setTimeout(r,10));assert.equal(counters.waiting,1);controller.abort();await pending;
 for(let i=0;i<100&&!counters.cancelled;i++)await new Promise(r=>setTimeout(r,10));assert.equal(counters.cancelled,1);
 assert.equal(await(await fetch(new URL('/health',resource))).text(),'fixture healthy');
 await client.close();server.closeAllConnections();await new Promise(r=>server.close(r));
 assert.equal((await wireMCPRoute({...wiring,command:'rollback'})).status,'unwired');
 assert.equal((await setupMCP({...options,command:'rollback'})).status,'removed');
 assert.equal(await readFile(join(project,'src/server.ts'),'utf8'),original);
 compile(); // Application still builds after removing the integration.
});
