import {lstat,readFile,readdir,realpath} from 'node:fs/promises';
import {join,relative,resolve,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import {verifyMCPRoute,loopbackMCPEndpoint,boundedMCPFetch} from './verify-mcp-route.mjs';

const routes=['/mcp','/.well-known/oauth-protected-resource/mcp'];
const skipped=new Set(['node_modules','dist','build','.git','.next','coverage','vendor']);
async function bounded(path,max=65536){
 const stat=await lstat(path);
 if(!stat.isFile()||stat.isSymbolicLink()||stat.size>max)return null;
 return readFile(path,'utf8');
}

/**
 * Static project detection. Reads bounded regular files only; never imports,
 * compiles or runs project code, and follows no symlinks.
 */
export async function detectMCPProject({project}){
 const root=await realpath(project);
 const sources=[];let scanned=0,truncated=false;
 const walk=async(dir,depth)=>{
  if(depth>6)return;
  for(const entry of (await readdir(dir,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){
   if(entry.isSymbolicLink()||skipped.has(entry.name)||entry.name.startsWith('.'))continue;
   const path=join(dir,entry.name);
   if(entry.isDirectory()){await walk(path,depth+1);continue;}
   if(!/\.(m|c)?(t|j)s$/.test(entry.name)||entry.name.endsWith('.d.ts'))continue;
   if(scanned>=400){truncated=true;return;}
   scanned++;const text=await bounded(path);if(text!==null)sources.push({rel:relative(root,path).split(sep).join('/'),text});
  }
 };
 await walk(root,0);
 let manifest=null;
 try{const text=await bounded(join(root,'package.json'));manifest=text===null?null:JSON.parse(text);}catch(e){if(e.code!=='ENOENT')manifest={invalid:true};}
 const goModule=await bounded(join(root,'go.mod')).catch(()=>null);
 const deps={...manifest?.devDependencies,...manifest?.dependencies};
 const lines=text=>text.split('\n').map(l=>l.trim());
 const candidates={
  optionsModules:sources.filter(s=>/export\s+const\s+mcpOptions\b/.test(s.text)).map(s=>s.rel),
  generatedHandlers:sources.filter(s=>s.text.startsWith('// Generated by WebDecoy MCP setup.')).map(s=>s.rel),
  routeFiles:sources.filter(s=>{const l=lines(s.text);return l.includes('// WEBDECOY:MCP_IMPORT')&&l.includes('// WEBDECOY:MCP_ROUTE');}).map(s=>s.rel),
  wiredRoutes:sources.filter(s=>s.text.includes('// WEBDECOY:MCP_ROUTE_BEGIN')).map(s=>s.rel),
  nodeServers:sources.filter(s=>/\bcreateServer\s*\(/.test(s.text)).map(s=>s.rel),
  // MCP servers built directly on the MCP SDK are not behind the WebDecoy handler.
  unwrappedMCPServers:sources.filter(s=>/\bnew\s+(McpServer|Server)\s*\(/.test(s.text)&&/@modelcontextprotocol\/sdk\/server/.test(s.text)).map(s=>s.rel),
 };
 const layouts=[],unsupported=[];
 const runtime=manifest?.invalid?'invalid_package_json':manifest?(manifest.type==='module'?'node-esm':'node-cjs'):goModule!==null?'go':'unknown';
 const typescript=sources.some(s=>/\.m?ts$/.test(s.rel));
 if(runtime==='node-esm'&&typescript&&(deps['@modelcontextprotocol/sdk']||candidates.optionsModules.length))layouts.push({layout:'node-http-mcp',support:'supported',guide:'examples/mcp/SETUP.md'});
 if(deps.next)layouts.push({layout:'nextjs',support:'separate_contract',guide:'NEXTJS.md',note:'Next.js route handlers use model admission, not these MCP wiring commands.'});
 for(const name of ['express','fastify','hono','koa'])if(deps[name])unsupported.push({layout:name,remediation:`Call protectedMCPHandler(req, res) for ${routes.join(' and ')} from a Node request callback. ${name} routing is not wired or verified by these commands.`});
 if(runtime==='node-cjs')unsupported.push({layout:'commonjs',remediation:'These commands support TypeScript Node ESM (package.json type=module).'});
 if(runtime==='go')unsupported.push({layout:'go',remediation:'Use the Go SDK for model admission and actions. There is no Go MCP adapter in this alpha.'});
 if(runtime==='node-esm'&&!typescript)unsupported.push({layout:'javascript',remediation:'The setup scaffold generates TypeScript; JavaScript projects need manual wiring and remain unverified.'});
 for(const file of candidates.unwrappedMCPServers)unsupported.push({layout:'unwrapped_mcp_server',file,remediation:'Tools registered on this MCP server bypass the WebDecoy handler. Move them into mcpOptions.tools or treat them as uncovered.'});
 const state=candidates.wiredRoutes.length&&candidates.generatedHandlers.length?'wired':candidates.generatedHandlers.length?'handler_generated':'not_integrated';
 const proposed=[];
 const one=list=>list.length===1?list[0]:null;
 const options=one(candidates.optionsModules),route=one(candidates.wiredRoutes)??one(candidates.routeFiles);
 if(layouts.some(l=>l.layout==='node-http-mcp')){
  if(!options)proposed.push({step:'select_options',action:candidates.optionsModules.length?`Choose one of ${candidates.optionsModules.join(', ')} and pass it explicitly.`:'Export mcpOptions typed as ProtectedMCPOptions from one TypeScript module, with trusted authenticate and per-tool authorize.'});
  else{
   const handler=options.replace(/[^/]+$/,'webdecoy-mcp.ts');
   if(state==='not_integrated')proposed.push({step:'setup',command:`node scripts/setup-mcp.mjs plan <project> ${options}`});
   if(!route)proposed.push({step:'add_markers',action:candidates.nodeServers.length?`Add one line "// WEBDECOY:MCP_IMPORT" among the imports and one line "// WEBDECOY:MCP_ROUTE" at the top of the request callback (req, res) in your server module, then rerun detect.`:'No Node request callback was found. Add the two marker lines to the module that handles HTTP requests, then rerun detect.'});
   else if(state!=='wired')proposed.push({step:'wire',command:`node scripts/wire-mcp-route.mjs plan <project> ${route} ${handler}`});
   proposed.push({step:'check',action:'Build and start the app on a loopback port, write a check plan with synthetic callers, then run: node scripts/doctor-mcp.mjs check <plan.json>'});
  }
 }
 return {schema:1,command:'detect',runtime,layouts,unsupported,state,candidates,proposed,filesScanned:scanned,truncated,executedProjectCode:false,
  coverage:'not_verified',remediation:layouts.length?'Review each proposed step; every command has a plan mode that changes nothing.':'No supported layout was detected. See the unsupported list for what to do instead.'};
}

const kinds=new Set(['allowed','forbidden','cross_tenant','cancellation']);
const deniedReasons={forbidden:new Set(['permission_denied','missing_scope','policy_denied','action_not_registered']),cross_tenant:new Set(['permission_denied','invalid_arguments','policy_denied'])};
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function readPlan(plan,env){
 if(!plan||plan.schema!==1||typeof plan!=='object')throw Error('Expected a schema 1 check plan');
 const endpoint=loopbackMCPEndpoint(plan.resource);
 if(plan.propertyId!==undefined&&!uuid.test(plan.propertyId))throw Error('propertyId must be a UUID');
 const callers=Object.entries(plan.callers??{});
 if(!callers.length||callers.length>4)throw Error('Name one to four synthetic callers');
 const tokens={};
 for(const [name,caller] of callers){
  if(!/^[a-z][a-z0-9_]{0,31}$/.test(name)||!/^[A-Z][A-Z0-9_]{0,63}$/.test(caller?.tokenEnv??''))throw Error('Each caller needs a lowercase name and an uppercase tokenEnv variable name');
  const token=env[caller.tokenEnv];
  if(typeof token!=='string'||!token||token.length>16384||/[\r\n]/.test(token))throw Error(`Set ${caller.tokenEnv} to a synthetic test credential`);
  tokens[name]=token;
 }
 if(!Array.isArray(plan.checks)||!plan.checks.length||plan.checks.length>32)throw Error('List one to 32 checks');
 for(const c of plan.checks){
  if(!kinds.has(c?.kind)||!Object.hasOwn(tokens,c.caller)||typeof c.tool!=='string'||!c.tool||c.tool.length>128)throw Error('Each check needs a kind, a named caller and a tool');
  if(c.arguments!==undefined&&(typeof c.arguments!=='object'||c.arguments===null||Array.isArray(c.arguments)||JSON.stringify(c.arguments).length>4096))throw Error('Check arguments must be a JSON object up to 4 KiB');
  if(c.kind==='cancellation'&&!(Number.isInteger(c.afterMs)&&c.afterMs>=1&&c.afterMs<=5000))throw Error('Cancellation checks need afterMs from 1 to 5000');
 }
 return {endpoint,tokens,checks:plan.checks,propertyId:plan.propertyId};
}
const actionError=result=>result?._meta?.['webdecoy.com/action-error'];

/**
 * Runs the customer's own synthetic calls against a selected loopback route
 * with the official client. Reports protocol evidence only: tool callbacks run
 * in the application's process and cannot be counted from here.
 */
export async function checkMCPRoute({plan,env=process.env,timeoutMs=3000}){
 const started=new Date();
 const report={schema:1,command:'check',passed:false,route:null,checks:[],
  exercised:{routes:[],tools:[],callers:0},
  notExercised:['runtime outages (not injected by this command)','alternate routes and unwrapped handlers','model budgets and request correlation (fetch/Next.js admission)','incremental tool progress'],
  callbacks:'not_observable_out_of_process',browserReceipts:'not_required_for_machine_callers',effectiveControls:'run inspectMCPControls(mcpOptions) in your process'};
 let parsed;
 try{parsed=readPlan(plan,env);}catch(e){report.checks.push({name:'plan',status:'unconfigured',remediation:e.message});return report;}
 const {endpoint,tokens,checks,propertyId}=parsed,first=Object.keys(tokens)[0];
 report.route=await verifyMCPRoute({resource:endpoint.href,token:tokens[first],timeoutMs:Math.min(timeoutMs,10000)});
 report.exercised.routes=report.route.passed?[...routes]:[];
 const clients={};
 try{
  if(!report.route.passed){for(const c of checks)report.checks.push({kind:c.kind,tool:c.tool,caller:c.caller,status:'not_run',remediation:'Fix the route checks first.'});return report;}
  const connect=async name=>{
   if(clients[name])return clients[name];
   const client=new Client({name:'webdecoy-doctor',version:'1'});
   await client.connect(new StreamableHTTPClientTransport(endpoint,{fetch:boundedMCPFetch(endpoint,timeoutMs),requestInit:{headers:{Authorization:`Bearer ${tokens[name]}`}}}));
   return clients[name]=client;
  };
  for(const c of checks){
   const entry={kind:c.kind,tool:c.tool,caller:c.caller};const began=performance.now();
   try{
    const client=await connect(c.caller);
    if(c.kind==='cancellation'){
     const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),c.afterMs);
     const outcome=await client.callTool({name:c.tool,arguments:c.arguments??{}},undefined,{signal:controller.signal,timeout:timeoutMs+c.afterMs}).then(()=>'completed',e=>controller.signal.aborted?'cancelled':'failed');
     clearTimeout(timer);
     await client.ping();
     Object.assign(entry,outcome==='cancelled'?{status:'verified',observed:'cancelled; server still answers'}:
      outcome==='completed'?{status:'inconclusive',observed:'completed before cancellation',remediation:'Choose a tool that waits on its abort signal, or lower afterMs.'}:
      {status:'failed',observed:'call failed before cancellation',remediation:'Check that the caller may call this tool, then retry.'});
    }else{
     const result=await client.callTool({name:c.tool,arguments:c.arguments??{}},undefined,{timeout:timeoutMs});
     const denial=actionError(result),actionId=result?._meta?.['webdecoy.com/action']?.actionId;
     if(typeof actionId==='string'&&uuid.test(actionId))entry.actionId=actionId.toLowerCase();
     if(c.kind==='allowed')Object.assign(entry,!result.isError?{status:'verified',observed:'allowed'}:
      {status:'failed',observed:denial?{reason:denial.reason,status:denial.status}:'tool error',remediation:denial?`Expected an allowed call but WebDecoy denied it (${denial.reason}). Check authenticate, requiredScopes, validate and authorize for this tool, and the plan's arguments.`:'The tool ran and reported an error. Check the application callback.'});
     else Object.assign(entry,denial&&deniedReasons[c.kind].has(denial.reason)?{status:'verified',observed:{reason:denial.reason,status:denial.status}}:
      !result.isError?{status:'failed',observed:'allowed',remediation:c.kind==='forbidden'?'This caller was allowed. Add requiredScopes or make authorize() return false for it.':'Another tenant\'s resource was allowed. authorize() must compare the trusted caller.tenant with the resource owner, not a caller-supplied argument.'}:
      {status:'failed',observed:denial?{reason:denial.reason,status:denial.status}:'tool error',remediation:'Refused for a different reason than expected; the check does not prove this control. Review the plan and the tool definition.'});
    }
   }catch(e){
    // A scope-gated tool is refused at HTTP level before any MCP message is processed.
    if(e?.code===403&&c.kind==='forbidden')Object.assign(entry,{status:'verified',observed:{reason:'insufficient_scope',status:403}});
    else Object.assign(entry,{status:'failed',observed:e?.code?{httpStatus:e.code}:'request_failed',remediation:'The request did not complete. Check the server is running, the tool exists and the token is valid; no automatic retry was made.'});
   }
   entry.durationMs=Math.round(performance.now()-began);
   report.checks.push(entry);
  }
 }finally{await Promise.all(Object.values(clients).map(c=>c.close().catch(()=>{})));}
 report.exercised.tools=[...new Set(checks.map(c=>c.tool))].sort();
 report.exercised.callers=Object.keys(clients).length;
 report.passed=report.checks.every(c=>c.status==='verified');
 const finished=new Date();
 report.window={from:started.toISOString(),to:finished.toISOString()};
 // Link the first call that returned an action ID (alpha.19+). Older servers get the page and window.
 const linked=report.checks.find(c=>c.actionId);
 report.dashboard=propertyId?{url:`https://app.webdecoy.com/ai-protection?property=${propertyId.toLowerCase()}${linked?`&action=${linked.actionId}`:''}`,locate:`Action results for ${report.exercised.tools.join(', ')} between ${report.window.from} and ${report.window.to}`,individuallyLinked:!!linked,
  ...(linked?{linkedCheck:{kind:linked.kind,tool:linked.tool,actionId:linked.actionId}}:{}),
  note:'Appears only if the server reports to WebDecoy (sharedRuntime). Reporting is best effort; absence here is not proof the call ran.'}:{url:null,note:'Add propertyId to the plan to get the dashboard location.'};
 return report;
}

if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){
 try{
  const [command,target,...extra]=process.argv.slice(2);
  if(extra.length||!target)throw Error('Use: detect <project> | check <plan.json>');
  let result;
  if(command==='detect')result=await detectMCPProject({project:target});
  else if(command==='check'){
   const text=await bounded(resolve(target),16384);if(text===null)throw Error('Plan must be a regular file up to 16 KiB');
   result=await checkMCPRoute({plan:JSON.parse(text)});
  }else throw Error('Use: detect <project> | check <plan.json>');
  console.log(JSON.stringify(result,null,2));
  if(command==='check'&&!result.passed)process.exitCode=1;
 }catch(e){console.error(`MCP doctor stopped: ${e instanceof SyntaxError?'invalid JSON':e.code??e.message}`);process.exitCode=1;}
}
