import {readFile,lstat,realpath,open,unlink} from 'node:fs/promises';
import {resolve,relative,dirname,basename,join,sep} from 'node:path';
import {pathToFileURL} from 'node:url';

const safePath=/^[A-Za-z0-9_./-]+$/;
async function regular(path,max=65536){
 const stat=await lstat(path);
 if(!stat.isFile()||stat.isSymbolicLink()||stat.size>max)throw Error('Expected a bounded regular file');
 return readFile(path,'utf8');
}
export async function setupMCP({command,project,optionsFile}) {
 if(!['plan','apply','rollback'].includes(command))throw Error('Use plan, apply or rollback');
 if(typeof optionsFile!=='string'||!safePath.test(optionsFile)||!optionsFile.endsWith('.ts'))throw Error('Select a relative TypeScript options module');
 const root=await realpath(project),source=resolve(root,optionsFile);
 const rel=relative(root,source);
 if(!rel||rel.startsWith('..'+sep)||rel==='..'||resolve(optionsFile)===optionsFile)throw Error('Options module must be inside the project');
 // Reject symlinks in every directory component, including the options file.
 let part=root;
 for(const segment of rel.split(sep)){part=join(part,segment);if((await lstat(part)).isSymbolicLink())throw Error('Symlinked module paths are unsupported');}
 await regular(source);
 const manifest=JSON.parse(await regular(join(root,'package.json')));
 const dependencies={...manifest.devDependencies,...manifest.dependencies};
 const required={'@webdecoy/ai-protection':'0.1.0-alpha.19','@modelcontextprotocol/sdk':'1.31.0'};
 const checks=Object.entries(required).map(([name,version])=>({name,status:dependencies[name]===version?'configured':'unverified',remediation:`Use the tested exact version ${name}@${version}; other ranges require separate verification.`}));
 checks.push({name:'esm',status:manifest.type==='module'?'configured':'unsupported',remediation:'This scaffold supports TypeScript Node ESM projects with package.json type=module.'});
 const target=join(dirname(source),'webdecoy-mcp.ts');
 if(target===source)throw Error('Select the options module, not the generated handler');
 const content=`// Generated by WebDecoy MCP setup. Review before connecting to your route.\nimport {createProtectedMCPHandler} from '@webdecoy/ai-protection/mcp';\nimport type {ProtectedMCPOptions} from '@webdecoy/ai-protection/mcp';\nimport {mcpOptions} from './${basename(source,'.ts')}.js';\n\n// Your options must include trusted authentication and per-tool authorization.\nexport const protectedMCPHandler = createProtectedMCPHandler(\n  mcpOptions satisfies ProtectedMCPOptions,\n);\n`;
 let existing;
 try{existing=await regular(target);}catch(e){if(e.code!=='ENOENT')throw e;}
 const report={schema:1,command,selectedOptions:rel,generatedHandler:relative(root,target),route:'/mcp',checks,coverage:'not_verified',unverified:['options export and type compatibility','route wiring and alternate handlers','authentication and tenant ownership','property credentials and runtime contract','effective limits and failure policies','report delivery and request correlation','allowed/denied/cancellation/outage behavior'],browserReceipts:'not_required_for_machine_callers',modelBudget:'not_verified',remediation:'Export mcpOptions typed as ProtectedMCPOptions. Review the diff, compile in your own build, wire only the selected /mcp route, then run the owned verification workload.'};
 if(command==='plan')return {...report,status:existing===undefined?'proposed':existing===content?'already_generated':'conflict',diff:existing===undefined?`--- /dev/null\n+++ ${relative(root,target)}\n@@ -0,0 +1,${content.trimEnd().split('\n').length} @@\n${content.trimEnd().split('\n').map(l=>'+'+l).join('\n')}\n`:null};
 if(command==='apply'){
  if(existing===content)return {...report,status:'unchanged'};
  if(existing!==undefined)throw Error('Handler exists and differs; review it manually. No changes made.');
  if(checks.some(c=>c.status!=='configured'))throw Error('Resolve package checks with plan before applying');
  const file=await open(target,'wx',0o644);
  try{await file.writeFile(content);}finally{await file.close();}
  return {...report,status:'created'};
 }
 if(existing===undefined)return {...report,status:'absent'};
 if(existing!==content)throw Error('Handler was edited; rollback refused. Preserve or remove it manually.');
 await unlink(target);return {...report,status:'removed'};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){
 try{const [command,project,optionsFile,...extra]=process.argv.slice(2);if(extra.length)throw Error('Unexpected arguments');console.log(JSON.stringify(await setupMCP({command,project,optionsFile}),null,2));}
 catch(e){console.error(`MCP setup stopped: ${e.code??(e instanceof SyntaxError?'Invalid package JSON':e.message)}`);process.exitCode=1;}
}
